import img1 from "../Assets/Images/chatgpt1.jpg"
import img2 from "../Assets/Images/chatgpt2.jpg"
import img3 from "../Assets/Images/chatgpt3.jpg"
import img4 from "../Assets/Images/chatgpt4.jpg"
import img5 from "../Assets/Images/chatgpt5.jpg"
import img6 from "../Assets/Images/chatgpt6.jpg"
import img7 from "../Assets/Images/chatgpt7.jpg"
import img8 from "../Assets/Images/chatgpt8.jpg"
import img9 from "../Assets/Images/chatgpt9.jpg"
import img10 from "../Assets/Images/chatgpt10.jpg"
import img11 from "../Assets/Images/chatgpt11.jpg"
import img12 from "../Assets/Images/chatgpt12.jpg"
import img13 from "../Assets/Images/chatgpt13.jpg"
import img14 from "../Assets/Images/chatgpt14.jpg"
import img15 from "../Assets/Images/chatgpt15.jpg"
import img16 from "../Assets/Images/chatgpt16.jpg"






export const Gpt_courses = [
        {
            id: 301,
            title: "Mastering ChatGPT: The Ultimate Guide to AI Conversations",
            description: "Learn how to leverage ChatGPT for creating intelligent conversations and automating customer service with ease.",
            instructor: "John Doe",
            rating: 4.8,
            rice: "29.99",
            category: "AI & Machine Learning",
            duration: "12 hours",
            level: "Beginner to Intermediate",
            language: "English",
            enrollment_count: 150000,
            images : img1,
       
        },
        {
           id: 302,
            title: "Build AI Chatbots with GPT-3 and ChatGPT",
            description: "Step-by-step guide to building AI chatbots using GPT-3 and ChatGPT to automate tasks and provide smart assistance.",
            instructor: "Emily White",
            rating: 4.7,
            price: "24.99",
            category: "AI & Chatbots",
            duration: "15 hours",
            level: "Intermediate",
            language: "English",
            enrollment_count: 120000,
            images: img2,
        },
        {
           id: 303,
            title: "ChatGPT for Beginners: How to Use ChatGPT in Daily Life",
            description: "A beginner's guide to using ChatGPT for personal and professional tasks, including writing, research, and learning.",
            instructor: "Robert James",
            rating: 4.6,
            price: "19.99",
            category: "Productivity",
            duration: "8 hours",
            level: "Beginner",
            language: "English",
            enrollment_count: 100000,
            images: img3,
        },
        {
            id: 304,
            title: "Creating Chatbots with GPT-3 for Business Applications",
            description: "Learn how to create intelligent chatbots using GPT-3 for automating customer service, sales, and lead generation.",
            instructor: "Sarah Green",
            rating: 4.9,
            price: "39.99",
            category: "Business & AI",
            duration: "20 hours",
            level: "Intermediate to Advanced",
            language: "English",
            enrollment_count: 180000,
            images: img4
        },
        {
            id: 305,
            title: "Advanced ChatGPT Development: Creating Complex AI Conversations",
            description: "Learn advanced techniques for creating complex conversations with ChatGPT, including personalized interactions and multi-turn dialogues.",
            instructor: "Mark Taylor",
            rating: 4.8,
            price: "49.99",
            category: "AI Development",
            duration: "25 hours",
            level: "Advanced",
            language: "English",
            enrollment_count: 70000,
            images: img5,
        },
        {
            id: 306,
            title: "ChatGPT for Content Creation: Writing, Blogging & Marketing",
            description: "Unlock the potential of ChatGPT for content creation, from blog posts to marketing copy and social media content.",
            instructor: "Jessica Lee",
            rating: 4.7,
            price: "19.99",
            category: "Marketing & Content Creation",
            duration: "10 hours",
            level: "Beginner to Intermediate",
            language: "English",
            enrollment_count: 85000,
            images: img6,
        },
        {
            id: 307,
            title: "ChatGPT in Education: Creating AI-Powered Tutoring Systems",
            description: "Learn how to integrate ChatGPT into education for tutoring, personalized learning, and virtual classrooms.",
            instructor: "Michael Harris",
            rating: 4.8,
            price: "29.99",
            category: "Education & AI",
            duration: "18 hours",
            level: "Intermediate",
            language: "English",
            enrollment_count: 95000,
            images: img7
        },
        {
             id: 308,
            title: "Automating Customer Support with ChatGPT and GPT-3",
            description: "Explore how to use ChatGPT for automating customer service tasks, creating effective help desks and reducing response time.",
            instructor: "Lily Adams",
            rating: 4.7,
            price: "34.99",
            category: "Business & AI",
            duration: "22 hours",
            level: "Intermediate",
            language: "English",
            enrollment_count: 120000,
            images: img8,
        },
        {
            id: 309,
            title: "ChatGPT for Freelancers: Automating Workflows and Communication",
            description: "Use ChatGPT to automate client communication, task management, and content creation to boost your productivity as a freelancer.",
            instructor: "James Anderson",
            rating: 4.8,
            price: "24.99",
            category: "Freelancing & Productivity",
            duration: "14 hours",
            level: "Beginner to Intermediate",
            language: "English",
            enrollment_count: 110000,
            images: img9,
        },
        {
            id: 310,
            title: "Building Personal Assistant Applications with ChatGPT",
            description: "Learn how to build AI-powered personal assistant applications using ChatGPT that can handle scheduling, reminders, and more.",
            instructor: "David Clark",
            rating: 4.9,
            price: "39.99",
            category: "AI Development",
            duration: "28 hours",
            level: "Advanced",
            language: "English",
            enrollment_count: 140000,
            images: img10,
        },
        {
            id: 311,
            title: "ChatGPT for Writing: Automating Content Generation",
            description: "Learn how to use ChatGPT to automate content writing tasks, including blog posts, eBooks, and article generation.",
            instructor: "Anna Wilson",
            rating: 4.7,
            price: "19.99",
            category: "Writing & AI",
            duration: "12 hours",
            level: "Beginner",
            language: "English",
            enrollment_count: 80000,
            images: img11,
        },
        {
            id: 312,
            title: "Building AI-Powered Chatbots with GPT-3 and ChatGPT",
            description: "Learn how to create AI chatbots using GPT-3 and ChatGPT that can carry out intelligent conversations and automate tasks.",
            instructor: "David Miller",
            rating: 4.8,
            price: "39.99",
            category: "AI & Development",
            duration: "18 hours",
            level: "Intermediate",
            language: "English",
            enrollment_count: 160000,
            images: img12,
        },
        {
           id: 313,
            title: "Introduction to ChatGPT for Business Applications",
            description: "Get an overview of how ChatGPT can be used to automate business processes, enhance customer interaction, and boost productivity.",
            instructor: "Samantha Brown",
            rating: 4.7,
            price: "19.99",
            category: "Business",
            duration: "10 hours",
            level: "Beginner",
            language: "English",
            enrollment_count: 120000,
            images: img13,
        },
        {
            id: 314,
            title: "ChatGPT for Social Media: Automating Engagement & Posts",
            description: "Learn how to use ChatGPT for automating social media posts, responses, and engagements on platforms like Instagram, Facebook, and Twitter.",
            instructor: "Olivia Johnson",
            rating: 4.8,
            price: "29.99",
            category: "Social Media & AI",
            duration: "15 hours",
            level: "Intermediate",
            language: "English",
            enrollment_count: 100000,
            images: img14,
        },
        {
            id: 315,
            title: "ChatGPT for Marketing: Enhance Your Campaigns with AI",
            description: "Leverage ChatGPT to optimize marketing campaigns, write copy, and create personalized content that engages your audience.",
            instructor: "Peter Moore",
            rating: 4.9,
            price: "34.99",
            category: "Marketing & AI",
            duration: "20 hours",
            level: "Intermediate to Advanced",
            language: "English",
            enrollment_count: 140000,
            images: img15,
        },
        {
           id: 316,
            title: "ChatGPT in Healthcare: Automating Patient Interaction",
            description: "Discover how ChatGPT can be used to automate patient inquiries, appointment scheduling, and follow-up care in healthcare.",
            instructor: "Laura Carter",
            rating: 4.7,
            price: "29.99",
            category: "Healthcare & AI",
            duration: "22 hours",
            level: "Intermediate",
            language: "English",
            enrollment_count: 95000,
            images: img16,
        },
    ]


