import img1 from "../Assets/Images/ss1.jpg"
import img2 from "../Assets/Images/ss2.jpg"
import img3 from "../Assets/Images/ss3.jpg"
import img4 from "../Assets/Images/ss4.jpg"
import img5 from "../Assets/Images/ss5.jpg"
import img6 from "../Assets/Images/ss6.jpg"
import img7 from "../Assets/Images/ss7.jpg"
import img8 from "../Assets/Images/ss8.jpg"
import img9 from "../Assets/Images/ss9.jpg"
import img10 from "../Assets/Images/ss10.jpg"
import img11 from "../Assets/Images/ss11.jpg"
import img12 from "../Assets/Images/ss12.jpg"
import img13 from "../Assets/Images/ss13.jpg"
import img14 from "../Assets/Images/ss14.jpg"
import img15 from "../Assets/Images/ss15.jpg"
import img16 from "../Assets/Images/ss16.jpg"
import img17 from "../Assets/Images/ss17.jpg"
import img18 from "../Assets/Images/ss18.jpg"
import img19 from "../Assets/Images/ss19.jpg"


export const SS_courses = [
        {
            id: 401,
            title: "Mastering Communication Skills",
            description: "Learn how to communicate effectively in both professional and personal settings with a focus on clarity and empathy.",
            instructor: "John Smith",
            rating: 4.8,
            price: "$19.99",
            category: "Soft Skills",
            duration: "10 hours",
            level: "Beginner",
            language: "English",
            enrollment_count: 120000,
            images: img1,
        },
        {
            id: 402,
            title: "Emotional Intelligence at Work",
            description: "Develop your emotional intelligence to improve relationships, manage stress, and enhance leadership skills.",
            instructor: "Jane Doe",
            rating: 4.7,
            price: "$24.99",
            category: "Soft Skills",
            duration: "15 hours",
            level: "Intermediate",
            language: "English",
            enrollment_count: 150000,
            images: img2,
        },
        {
            id: 403,
            title: "Time Management Mastery",
            description: "Master time management techniques to boost your productivity, meet deadlines, and maintain a work-life balance.",
            instructor: "Richard Lee",
            rating: 4.9,
            price: "$19.99",
            category: "Soft Skills",
            duration: "12 hours",
            level: "Beginner to Intermediate",
            language: "English",
            enrollment_count: 100000,
            images: img3,
        },
        {
           id: 404,
            title: "The Art of Negotiation",
            description: "Learn how to negotiate effectively in business and personal situations to achieve win-win outcomes.",
            instructor: "David Harris",
            rating: 4.8,
            price: "$29.99",
            category: "Soft Skills",
            duration: "18 hours",
            level: "Intermediate",
            language: "English",
            enrollment_count: 80000,
            images: img4,
        },
        {
            id: 405,
            title: "Leadership Skills for Managers",
            description: "Develop essential leadership skills to inspire, motivate, and lead teams toward success.",
            instructor: "Sarah Thompson",
            rating: 4.7,
            price: "$34.99",
            category: "Soft Skills",
            duration: "20 hours",
            level: "Intermediate to Advanced",
            language: "English",
            enrollment_count: 120000,
            images: img5,
        },
        {
            id: 406,
            title: "Building Confidence and Self-Esteem",
            description: "Boost your confidence and self-esteem to improve your personal and professional life.",
            instructor: "Michael Brown",
            rating: 4.8,
            price: "$19.99",
            category: "Soft Skills",
            duration: "10 hours",
            level: "Beginner",
            language: "English",
            enrollment_count: 130000,
            images: img6,
        },
        {
            id: 407,
            title: "Public Speaking and Presentation Skills",
            description: "Enhance your public speaking and presentation skills to effectively communicate and captivate your audience.",
            instructor: "Lily White",
            rating: 4.9,
            price: "$27.99",
            category: "Soft Skills",
            duration: "15 hours",
            level: "Beginner to Intermediate",
            language: "English",
            enrollment_count: 160000,
            images: img7,
        },
        {
            id: 408,
            title: "Conflict Resolution and Mediation Skills",
            description: "Learn conflict resolution techniques to manage disputes, improve collaboration, and maintain harmony in the workplace.",
            instructor: "James Davis",
            rating: 4.7,
            price: "$22.99",
            category: "Soft Skills",
            duration: "14 hours",
            level: "Intermediate",
            language: "English",
            enrollment_count: 70000,
            images: img8,
        },
        {
            id: 409,
            title: "Building Strong Interpersonal Skills",
            description: "Enhance your interpersonal communication skills to build better relationships in both personal and professional settings.",
            instructor: "Olivia Johnson",
            rating: 4.8,
            price: "$19.99",
            category: "Soft Skills",
            duration: "12 hours",
            level: "Beginner",
            language: "English",
            enrollment_count: 110000,
            images: img9,
        },
        {
            course_id: 410,
            title: "Creative Problem Solving and Critical Thinking",
            description: "Develop creative problem-solving and critical thinking skills to address challenges in innovative ways.",
            instructor: "George Allen",
            rating: 4.7,
            price: "$24.99",
            category: "Soft Skills",
            duration: "16 hours",
            level: "Intermediate",
            language: "English",
            enrollment_count: 95000,
            images: img10,
        },
        {
            id: 411,
            title: "Active Listening Skills for Effective Communication",
            description: "Learn active listening techniques to improve your communication and better understand others.",
            instructor: "Sophie Brown",
            rating: 4.9,
            price: "$19.99",
            category: "Soft Skills",
            duration: "8 hours",
            level: "Beginner",
            language: "English",
            enrollment_count: 105000,
            images: img11,
        },
        {
            id: 412,
            title: "Emotional Intelligence for Leaders",
            description: "Master the art of emotional intelligence to lead with empathy, understand others, and make better decisions.",
            instructor: "John Green",
            rating: 4.8,
            price: "$34.99",
            category: "Leadership",
            duration: "20 hours",
            level: "Intermediate to Advanced",
            language: "English",
            enrollment_count: 85000,
            images: img12,
        },
        {
            id: 413,
            title: "Team Building and Collaboration Skills",
            description: "Learn the key principles of team building and how to work effectively with diverse teams.",
            instructor: "Elizabeth Miller",
            rating: 4.8,
            price: "$29.99",
            category: "Soft Skills",
            duration: "18 hours",
            level: "Intermediate",
            language: "English",
            enrollment_count: 95000,
            images: img13,
        },
        {
            id: 414,
            title: "Managing Stress and Building Resilience",
            description: "Learn techniques to manage stress effectively and build resilience for a healthier, more productive life.",
            instructor: "Chris Walker",
            rating: 4.7,
            price: "$22.99",
            category: "Soft Skills",
            duration: "14 hours",
            level: "Beginner to Intermediate",
            language: "English",
            enrollment_count: 115000,
            images: img14,
        },
        {
            id: 415,
            title: "Critical Thinking for Problem Solving",
            description: "Improve your critical thinking skills to analyze problems, make better decisions, and find creative solutions.",
            instructor: "Michael Rodriguez",
            rating: 4.7,
            price: "$19.99",
            category: "Soft Skills",
            duration: "10 hours",
            level: "Beginner",
            language: "English",
            enrollment_count: 90000,
            images: img15,
        },
        {
            id: 416,
            title: "The Art of Persuasion and Influence",
            description: "Learn techniques to persuade and influence others effectively in both personal and professional settings.",
            instructor: "Anna Lewis",
            rating: 4.9,
            price: "$34.99",
            category: "Soft Skills",
            duration: "20 hours",
            level: "Intermediate",
            language: "English",
            enrollment_count: 140000,
            images: img16,
        },
        {
            id: 417,
            title: "Building a Growth Mindset",
            description: "Develop a growth mindset to overcome challenges, embrace learning, and achieve personal and professional growth.",
            instructor: "David Cooper",
            rating: 4.8,
            price: "$19.99",
            category: "Soft Skills",
            duration: "10 hours",
            level: "Beginner",
            language: "English",
            enrollment_count: 125000,
            images: img17,
        },
        {
           id: 418,
            title: "Negotiation Skills for Success",
            description: "Master negotiation techniques to reach mutually beneficial agreements in any professional or personal scenario.",
            instructor: "Richard Collins",
            rating: 4.8,
            price: "$24.99",
            category: "Soft Skills",
            duration: "18 hours",
            level: "Intermediate",
            language: "English",
            enrollment_count: 100000,
            images: img18,
        },
        {
            id: 419,
            title: "Conflict Management in the Workplace",
            description: "Learn how to manage and resolve conflicts at work to create a positive and productive environment.",
            instructor: "Linda Perez",
            rating: 4.7,
            price: "$19.99",
            category: "Soft Skills",
            duration: "12 hours",
            level: "Intermediate",
            language: "English",
            enrollment_count: 85000,
            images: img19,
        }
    ]

