import img1 from "../Assets/Images/trd1.jpg"
import img2 from "../Assets/Images/trd2.jpg"
import img3 from "../Assets/Images/trd3.jpg"
import img4 from "../Assets/Images/trd4.jpg"
import img5 from "../Assets/Images/trd5.jpg"
import img6 from "../Assets/Images/trd6.jpg"
import img7 from "../Assets/Images/trd7.jpg"
import img8 from "../Assets/Images/trd8.jpg"
import img9 from "../Assets/Images/trd9.jpg"
import img10 from "../Assets/Images/trd10.jpg"
import img11 from "../Assets/Images/trd11.jpg"
import img12 from "../Assets/Images/trd12.jpg"
import img13 from "../Assets/Images/trd13.jpg"
import img14 from "../Assets/Images/trd14.jpg"
import img15 from "../Assets/Images/trd15.jpg"
import img16 from "../Assets/Images/trd16.jpg"
import img17 from "../Assets/Images/trd17.jpg"
import img18 from "../Assets/Images/trd18.jpg"
import img19 from "../Assets/Images/trd19.jpg"


export const Trd_courses = [
        {
             id: 501,
            title: "AI for Everyone: Introduction to Artificial Intelligence",
            description: "A beginner-friendly course that introduces the concepts of Artificial Intelligence and its real-world applications.",
            instructor: "Andrew Ng",
            rating: 4.9,
            price: "$19.99",
            category: "AI & Machine Learning",
            duration: "10 hours",
            level: "Beginner",
            language: "English",
             enrollment_count: 300000,
            images : img1,
        },
        {
           id: 502,
            title: "Master Python for Data Science and Machine Learning",
            description: "Learn Python programming, data analysis, and machine learning techniques using popular libraries such as Pandas, NumPy, and Scikit-learn.",
            instructor: "Chris Shaw",
            rating: 4.8,
            price: "$29.99",
            category: "Programming",
            duration: "20 hours",
            level: "Intermediate",
            language: "English",
            enrollment_count: 250000,
            images: img2,
        },
        {
            id: 503,
            title: "The Complete Web Developer Bootcamp 2024",
            description: "Master web development technologies, including HTML, CSS, JavaScript, Node.js, and more to become a full-stack developer.",
            instructor: "Colt Steele",
            rating: 4.9,
            price: "$39.99",
            category: "Web Development",
            duration: "50 hours",
            level: "Beginner to Intermediate",
            language: "English",
            enrollment_count: 350000,
            images: img3,
        },
        {
            id: 504,
            title: "Deep Learning A-Z™: Hands-On Artificial Neural Networks",
            description: "Comprehensive course on building neural networks and deep learning models with TensorFlow, Keras, and more.",
            instructor: "SuperDataScience Team",
            rating: 4.9,
            price: "$34.99",
            category: "AI & Machine Learning",
            duration: "24 hours",
            level: "Advanced",
            languag: "English",
            enrollment_count: 180000,
            images: img4,
        },
        {
            id: 505,
            title: "Mastering Data Science with Python and R",
            description: "Learn the essentials of data science with Python and R, covering data cleaning, data visualization, and machine learning algorithms.",
            instructor: "Jonas Schmedtmann",
            rating: 4.8,
            price: "$39.99",
            category: "Data Science",
            duration: "30 hours",
            level: "Intermediate",
            language: "English",
            enrollment_count: 120000,
            images: img5,
        },
        {
            course_id: 506,
            title: "Complete Guide to Kubernetes & Docker: DevOps for Beginners",
            description: "Learn how to deploy and manage applications with Docker and Kubernetes, and understand the essentials of DevOps.",
            instructor: "Nigel Thomas",
            rating: 4.8,
            price: "$34.99",
            category: "DevOps",
            duration: "25 hours",
            level: "Intermediate",
            language: "English",
            enrollment_count: 90000,
            images: img6,
        },
        {
            id: 507,
            title: "Complete Digital Marketing Course 2024",
            description: "Master SEO, social media marketing, email marketing, and more in this comprehensive digital marketing course.",
            instructor: "Udemy Team",
            rating: 4.7,
            price: "$29.99",
            category: "Marketing",
            duration: "40 hours",
            level: "Beginner to Intermediate",
            language: "English",
            enrollment_count: 200000,
            images: img7,
        },
        {
            id: 508,
            title: "ChatGPT Mastery: Create & Integrate AI Chatbots",
            description: "Learn how to develop and integrate AI-powered chatbots using GPT-3 and ChatGPT for various applications.",
            instructor: "Sarah Miller",
            rating: 4.8,
            price: "$29.99",
            category: "AI & Development",
            duration: "15 hours",
            level: "Intermediate",
            language: "English",
            enrollment_count: 110000,
            images: img8,
        },
        {
            id: 509,
            title: "The Complete Guide to Ethical Hacking 2024",
            description: "Learn ethical hacking techniques to test and secure your systems, from penetration testing to network security.",
            instructor: "Alexander James",
            rating: 4.9,
            price: "$39.99",
            category: "Cybersecurity",
            duration: "30 hours",
            level: "Advanced",
            language: "English",
            enrollment_count: 180000,
            images: img9,
        },
        {
            id: 510,
            title: "Introduction to Blockchain and Cryptocurrency",
            description: "Learn the fundamentals of blockchain technology and how cryptocurrencies like Bitcoin work.",
            instructor: "Mark Robinson",
            rating: 4.7,
            price: "$24.99",
            category: "Blockchain",
            duration: "12 hours",
            level: "Beginner",
            language: "English",
            enrollment_count: 160000,
            images: img10,
        },
        {
            id: 511,
            title: "Excel to SQL: Data Analysis for Beginners",
            description: "Learn how to analyze data with Excel and SQL, two powerful tools for data analysts.",
            instructor: "David Green",
            rating: 4.8,
            price: "$19.99",
            category: "Data Science",
            duration: "16 hours",
            level: "Beginner",
            language: "English",
            enrollment_count: 130000,
            images: img11,
        },
        {
            id: 512,
            title: "Artificial Intelligence for Business Leaders",
            description: "Understand how AI can be used in business and gain the knowledge to lead AI-driven transformation in your company.",
            instructor: "Andrew Ng",
            rating: 4.9,
            price: "$49.99",
            category: "AI & Business",
            duration: "10 hours",
            level: "Beginner",
            language: "English",
            enrollment_count: 100000,
            images: img12,
        },
        {
            id: 513,
            title: "Cyber Security for Beginners: Protect Your Business Online",
            description: "Learn how to secure your online presence and protect your business from common cybersecurity threats.",
            instructor: "John Smith",
            rating: 4.8,
            price: "$24.99",
            category: "Cybersecurity",
            duration: "15 hours",
            level: "Beginner",
            language: "English",
            enrollment_count: 95000,
            images: img13,
        },
        {
            id: 514,
            title: "Mastering ChatGPT for Content Creation",
            description: "Learn how to use ChatGPT for content writing, blogging, and social media post generation.",
            instructor: "Anna Wilson",
            rating: 4.8,
            price: "$19.99",
            category: "Content Creation & AI",
            duration: "10 hours",
            level: "Beginner",
            language: "English",
            enrollment_count: 120000,
            images: img14,
        },
        {
            id: 515,
            title: "The Complete Graphic Design Bootcamp 2024",
            description: "Master the fundamentals of graphic design with Adobe Photoshop, Illustrator, and other essential tools.",
            instructor: "Daniel White",
            rating: 4.9,
            price: "$29.99",
            category: "Design",
            duration: "40 hours",
            level: "Beginner to Intermediate",
            language: "English",
            enrollment_count: 150000,
            images: img15,
        },
        {
            id: 516,
            title: "Data Science and Machine Learning Bootcamp with R",
            description: "Master data science and machine learning using R, from basic concepts to advanced techniques.",
            instructor: "Jason Lee",
            rating: 4.9,
            price: "$39.99",
            category: "Data Science & Machine Learning",
            duration: "30 hours",
            level: "Intermediate",
            language: "English",
            enrollment_count: 110000,
            images: img16,
        },
        {
            id: 517,
            title: "Python for Finance: Master Data Analysis and Algorithmic Trading",
            description: "Learn how to use Python to analyze financial data, build financial models, and automate trading strategies.",
            instructor: "Mark Harris",
            rating: 4.7,
            price: "$34.99",
            category: "Finance & Programming",
            duration: "20 hours",
            level: "Intermediate",
            language: "English",
            enrollment_count: 95000,
            images: img17,
        },
        {
            id: 518,
            title: "Complete AWS Certified Solutions Architect - Associate 2024",
            description: "Prepare for the AWS Certified Solutions Architect – Associate exam with comprehensive coverage of AWS services and architecture.",
            instructor: "Liam Johnson",
            rating: 4.8,
            price: "$49.99",
            category: "Cloud Computing",
            duration: "35 hours",
            level: "Intermediate to Advanced",
            language: "English",
            enrollment_count: 130000,
            images: img18,
        },
        {
            id: 519,
            title: "Data Visualization with Tableau: The Complete Guide",
            description: "Learn how to create stunning data visualizations and dashboards using Tableau for data-driven decision-making.",
            instructor: "Rachel Foster",
            rating: 4.8,
            price: "$24.99",
            category: "Data Science & Visualization",
            duration: "15 hours",
            level: "Intermediate",
            language: "English",
            enrollment_count: 100000,
            images: img19,
        }
    ]

