import img1 from "../Assets/Images/wd1.jpg"
import img2 from "../Assets/Images/wd2.jpg"
import img3 from "../Assets/Images/wd3.jpg"
import img4 from "../Assets/Images/wd4.jpg"
import img5 from "../Assets/Images/wd5.jpg"
import img6 from "../Assets/Images/wd6.jpg"
import img7 from "../Assets/Images/wd7.jpg"
import img8 from "../Assets/Images/wd8.jpg"
import img9 from "../Assets/Images/wd9.jpg"
import img10 from "../Assets/Images/wd10.jpg"
import img11 from "../Assets/Images/wd11.jpg"
import img12 from "../Assets/Images/wd12.jpg"
import img13 from "../Assets/Images/wd13.jpg"
import img14 from "../Assets/Images/wd14.jpg"
import img15 from "../Assets/Images/wd15.jpg"
import img16 from "../Assets/Images/wd16.jpg"
import img17 from "../Assets/Images/wd17.jpg"
import img18 from "../Assets/Images/wd18.jpg"
import img19 from "../Assets/Images/wd19.jpg"
import img20 from "../Assets/Images/wd20.jpg"

export const WD_courses = [
        {
            id: 601,
            title: "The Complete Web Developer Bootcamp 2024",
            description: "Master HTML, CSS, JavaScript, Node.js, and more to become a full-stack web developer.",
            instructor: "Colt Steele",
            rating: 4.9,
            price: "$39.99",
            category: "Web Development",
            duration: "50 hours",
            level: "Beginner to Intermediate",
            language: "English",
            enrollment_count: 350000,
            images : img1,
        },
        {
            id: 602,
            title: "Modern JavaScript From The Beginning",
            description: "Learn JavaScript from scratch in a project-based, hands-on approach for web development.",
            instructor: "Brad Traversy",
            rating: 4.8,
            price: "$29.99",
            category: "JavaScript",
            duration: "15 hours",
            level: "Beginner",
            language: "English",
            enrollment_count: 150000,
            images : img2,
        },
        {
            id: 603,
            title: "React - The Complete Guide (incl Hooks, React Router, Redux)",
            description: "Learn React.js and build powerful web applications with features like hooks, routing, and state management using Redux.",
            instructor: "Maximilian Schwarzmüller",
            rating: 4.9,
            price: "$39.99",
            category: "Web Development",
            duration: "40 hours",
            level: "Intermediate",
            language: "English",
            enrollment_count: 200000,
            images : img3
        },
        {
            id: 604,
            title: "The Complete Node.js Developer Course (3rd Edition)",
            description: "Learn to build web applications and RESTful APIs using Node.js, Express, MongoDB, and more.",
            instructor: "Andrew Mead",
            rating: 4.8,
            price: "$34.99",
            category: "Node.js",
            duration: "30 hours",
            level: "Intermediate",
            language: "English",
            enrollment_count: 180000,
            images : img4,
        },
        {
            id: 605,
            title: "The Complete Web Developer in 2024: Zero to Mastery",
            description: "Learn everything from HTML, CSS, JavaScript to back-end technologies and build full-stack applications.",
            instructor: "Andrei Neagoie",
            rating: 4.9,
            price: "$39.99",
            category: "Web Development",
            duration: "40 hours",
            level: "Beginner to Advanced",
            language: "English",
            enrollment_count: 220000,
            images : img5,
        },
        {
            id: 606,
            title: "Advanced CSS and Sass: Flexbox, Grid, Animations and More",
            description: "Master advanced CSS techniques and create modern, responsive web designs using Flexbox, CSS Grid, and animations.",
            instructor: "Jonas Schmedtmann",
            rating: 4.9,
            price: "$29.99",
            category: "CSS",
            duration: "16 hours",
            level: "Intermediate",
            language: "English",
            enrollment_count: 130000,
            images : img6,
        },
        {
            id: 607,
            title: "The Complete JavaScript Course 2024: From Zero to Expert",
            description: "Learn JavaScript from the ground up and master the fundamentals of programming, working with objects, functions, and more.",
            instructor: "Jonas Schmedtmann",
            rating: 4.9,
            price: "$39.99",
            category: "JavaScript",
            duration: "35 hours",
            level: "Beginner to Intermediate",
            language: "English",
            enrollment_count: 180000,
            images : img7,
        },
        {
            id: 608,
            title: "Vue - Vue JS 3 Mastery: Build Awesome Projects",
            description: "Learn Vue.js from basics to advanced concepts and build awesome, modern applications with the latest features.",
            instructor: "Eduardo S.",
            rating: 4.8,
            price: "$29.99",
            category: "Web Development",
            duration: "20 hours",
            level: "Intermediate",
            language: "English",
            enrollment_count: 120000,
            images : img8,
        },
        {
            id: 609,
            title: "Angular - Angular Crash Course (2024)",
            description : "Understand Angular fundamentals and build powerful web apps using components, services, and reactive forms.",
            instructor: "Brad Traversy",
            rating: 4.8,
            price: "$29.99",
            category: "Web Development",
            duration: "12 hours",
            level: "Beginner to Intermediate",
            language: "English",
            enrollment_count: 140000,
            images : img9
        },
        {
            id: 610,
            title: "Complete Guide to SQL for Web Developers",
            description: "Learn SQL and database management concepts and integrate them into your web development projects.",
            instructor: "Jonas Schmedtmann",
            rating: 4.8,
            price: "$24.99",
            category: "Web Development",
            duration: "18 hours",
            level: "Beginner",
            language: "English",
            enrollment_count: 100000,
            images : img10,
        },
        {
            id: 611,
            title: "Build Responsive Real-World Websites with HTML5 and CSS3",
            description: "Learn to create fully responsive websites using HTML5 and CSS3 with best practices in mind.",
            instructor: "Jonas Schmedtmann",
            rating: 4.9,
            price: "$19.99",
            category: "Web Development",
            duration: "14 hours",
            level: "Beginner",
            language: "English",
            enrollment_count: 150000,
            images : img11,
        },
        {
            id: 612,
            title: "The Ultimate Guide to React Native in 2024",
            description: "Learn how to develop mobile applications using React Native, covering components, navigation, and real-world applications.",
            instructor: "Maximilian Schwarzmüller",
            rating: 4.9,
            price: "39.99",
            category: "Mobile Development",
            duration: "30 hours",
            level: "Intermediate",
            language: "English",
            enrollment_count: 160000,
            images : img12,
        },
        {
            id: 613,
            title: "Master Git and GitHub for Web Developers",
            description: "Learn version control with Git and how to collaborate on code using GitHub in web development projects.",
            instructor: "Colt Steele",
            rating: 4.9,
            price: "$19.99",
            category: "Web Development",
            duration: "10 hours",
            level: "Beginner",
            language: "English",
            enrollment_count: 200000,
            images : img13,
        },
        {
            id: 614,
            title: "Complete Guide to CSS Grid",
            description: "Master CSS Grid to create modern, responsive layouts for your web pages without using floats or positioning.",
            instructor: "Jonas Schmedtmann",
            rating: 4.8,
            price: "$24.99",
            category: "CSS",
            duration: "10 hours",
            level: "Intermediate",
            language: "English",
            enrollment_count: 130000,
            images : img14,
        },
        {
            id: 615,
            title: "Building Real-World Web Applications with Django & Python",
            description : "Learn how to build full-fledged web applications with Python and Django, including back-end and front-end development.",
            instructor: "Brad Traversy",
            rating: 4.9,
            price: "$34.99",
            category: "Web Development",
            duration: "30 hours",
            level: "Intermediate",
            language: "English",
            enrollment_count: 150000,
            images : img15,
        },
        {
            id: 616,
            title: "Building REST APIs with Node.js",
            description: "Learn how to build scalable and efficient REST APIs with Node.js and Express, and connect them with databases.",
            instructor: "Andrew Mead",
            rating: 4.8,
            price: "$29.99",
            category: "Node.js",
            duration: "20 hours",
            level: "Intermediate",
            language: "English",
            enrollment_count: 110000,
            images : img16,
        },
        {
            id: 617,
            title: "Frontend Web Development with React",
            description: "Learn how to develop modern, interactive websites and web apps using React.js, Redux, and React Router.",
            instructor: "Mosh Hamedani",
            rating: 4.8,
            price: "$34.99",
            category: "React",
            duration: "25 hours",
            level: "Intermediate",
            language: "English",
            enrollment_count: 120000,
            images : img17,
        },
        {
            id: 618,
            title: "The Complete HTML5 and CSS3 Course: Build Responsive Websites",
            description: "Learn the fundamentals of HTML5 and CSS3 and how to build responsive websites for all devices.",
            instructor: "Jonas Schmedtmann",
            rating: 4.9,
            price: "29.99",
            category: "Web Development",
            duration: "18 hours",
            level: "Beginner",
            language: "English",
            enrollment_count: 110000,
            images : img18
        },
        {
            id: 619,
            title: "Building Full-Stack Web Apps with React, Redux, and Node.js",
            description: "Master full-stack development by building modern web applications with React, Redux, Node.js, and MongoDB.",
            instructor: "Brad Traversy",
            rating: 4.9,
            price: "$39.99",
            category: "Web Development",
            duration: "40 hours",
            level: "Intermediate",
            language: "English",
            enrollment_count: 100000,
            images : img19
        },
        {
            id: 620,
            title: "The Complete React Developer Course (w/ Hooks and Redux)",
            description: "Master React.js, React hooks, Redux, and React Router to build dynamic web applications.",
            instructor: "Andrew Mead",
            rating: 4.9,
            price: "34.99",
            category: "Web Development",
            duration: "30 hours",
            level: "Intermediate",
            language: "English",
            enrollment_count: 140000,
            images : img20,
        }
    ]

